### ISSUE TITLE
关于模型使用的特征以及样本问题

### ISSUE THREAD

**Issue by JJplane** [Stevenn9981/EDDA#1]
请问作者，所有的模型的特征都只使用了item和user这两个向量是吧，我看代码大概是这个实现。另外样本上的负样本，不仅是训练集，包括测试集，都是随机采样的。如果是这样的话，请问作者了解到哪个之前的工作也是采用了同样的方法呢。

**Comment by Stevenn9981** [comment]
User和item只用了ID embedding。另外因为数据集只有正样本，所以负样本只能通过随机采样而得到。因为现有的multi-domain的工作大多数来源于工业界，他们有更加丰富的用户数据。而开源数据中缺少真实负样本，已有工作中一般都是将不存在的user-item pairs作为负样本。因为负样本数量太多，所以这里做了随机采样

**Comment by JJplane** [comment]
> User和item只用了ID embedding。另外因为数据集只有正样本，所以负样本只能通过随机采样而得到。因为现有的multi-domain的工作大多数来源于工业界，他们有更加丰富的用户数据。而开源数据中缺少真实负样本，已有工作中一般都是将不存在的user-item pairs作为负样本。因为负样本数量太多，所以这里做了随机采样

了解了，感谢回复。开源样本集中是有正负样本的，比如aliccp和alimama的。而且现有的multi-domain的工作感觉也很少只用这两个emb，只用用户和item局限性太大了。感觉跟实际工业应用会有些差距，不过还是比较好的思路，再次感谢回复。
