### ISSUE TITLE
关于aliccp数据处理

### ISSUE THREAD

**Issue by cywuuuu** [Stevenn9981/EDDA#2]
请问作者是如何处理aliccp得到的graph呢？因为和原有数据集差距较大，想请教作者大致是怎样的处理流程，还希望您赐教！感激

**Comment by Stevenn9981** [comment]
我是在原数据中，按照item category作为domain，然后从原数据中采样了10个domain得到的。

**Comment by cywuuuu** [comment]
所以您是采样出了一部分item对吗，那还请问user您是如何采样的呢

**Comment by cywuuuu** [comment]
还是说，user就是之前按item category采样出item的record中的user

**Comment by Stevenn9981** [comment]
user就是之前按item category采样出item的record中的user

**Comment by cywuuuu** [comment]
好的感谢您！

**Comment by cywuuuu** [comment]
您好，我还遇到了一个问题忘记和您交流了，就是AliCCP这个数据集不同域间的样本数量是较不均衡，这样按前面这种方式采样的话我发现采样出来的数据也是存在样本量分布差距较大的问题，还请问作者是如何解决的呢？请您指教了<img width="299" alt="b90b8aa55afe28435e6524c654b475c" src="https://github.com/Stevenn9981/EDDA/assets/87512167/f66d9bfd-41d7-47b6-9491-115f1f51c8ad">

**Comment by Stevenn9981** [comment]
这个是正常的，我没有对这个做限制。不同的domain间样本量是可能差距很大的。
